package com.sbg.bdd.cucumber.screenplay.scoped

import com.sbg.bdd.cucumber.screenplay.core.formatter.ScreenPlayFormatter
import com.sbg.bdd.cucumber.screenplay.scoped.plugin.CucumberPayloadProducingListener
import groovy.json.JsonSlurper

import static java.util.Arrays.asList

class WhenFormattingGherkinJsonFromScreenplayEvents extends WhenScopeXYZ {
    def 'should reflect the same report json as that generated by the ScreenplayFormatter'(){
        given:
        def report = new StringBuilder()

        def formatter = new ScreenPlayFormatter(report)
        SamplePayloadProducingListener.output= formatter
        when:
        def expected = runFeaturesWithScreenplayPlugin(asList("classpath:cucumber/scoping/ScopedStuff.feature"))
        formatter.done()
        def jsonSlurper = new JsonSlurper()
        def found = jsonSlurper.parseText(report.toString())
        then:
        expected == found
        println report
    }
    }
