package com.sbg.bdd.screenplay.core.annotations;

public enum ActorEventType {
    BEFORE_PERSONA_LOADED,AFTER_PERSONA_LOADED,BEFORE_ABILITY_ADDED, AFTER_ABILITY_ADDED,BEFORE_DISMISSED,AFTER_DISMISSED
}
